"""Export the lagrum EBNF grammars and datasets for the static SPA."""

import json
from pathlib import Path
import sys

# Ensure ferenda is importable
REPO_ROOT = Path(__file__).resolve().parents[2] / "ferenda"
if not REPO_ROOT.exists():
    REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ferenda.lib import datasets, resolve
from ferenda.lib.lagrum import (
    ALL_PARSE_TYPES,
    ATTRIBUTE_ORDER,
    DEPENDS,
    EDPB_NAMES,
    EU_EXTRA_RULES,
    EU_KEYS,
    EU_NAMNAKT_RULES,
    EU_RULES_ENG,
    EU_TERMINALS,
    EU_TRIGGER_SRC_ENG,
    FORESKRIFT_TRIGGER_SRC,
    FRAGMENT_LETTERS,
    FS_DESIGNATIONS,
    FS_SLUG,
    INDEFINITE_HEADS,
    KORTLAGRUM,
    LAGRUM,
    LAW_SYNONYMS,
    NOLAW,
    ORDINALS,
    ROOTS,
    RULES,
    TERMINALS,
    TREATIES,
    TREATY_PIN,
    TRIGGER_SRC,
    TYPE_ORDER,
    WP29_GROUP,
    LagrumParser,
    _jo_arsberattelse,
    load_abbreviations,
    load_namedacts,
    load_namedlaws,
)

OUTPUT_DIR = REPO_ROOT / "slopcheck" / "src" / "lagrum"


def build_grammar_js():
    return """// Auto-generated by slopcheck/scripts/export-lagrum.py - DO NOT EDIT MANUALLY

export const TYPE_ORDER = %s;

export const DEPENDS = %s;

export const ROOTS = %s;

export const RULES = %s;

export const TERMINALS = %s;

export const EU_TERMINALS = %s;

export const EU_EXTRA_RULES = %s;

export const EU_NAMNAKT_RULES = %s;

export const TRIGGER_SRC = %s;

export const EU_TRIGGER_SRC_ENG = %s;

export const EU_RULES_ENG = %s;
""" % (
        json.dumps(TYPE_ORDER, indent=2),
        json.dumps(DEPENDS, indent=2),
        json.dumps(ROOTS, indent=2),
        json.dumps(RULES, indent=2),
        json.dumps(TERMINALS),
        json.dumps(EU_TERMINALS, indent=2),
        json.dumps(EU_EXTRA_RULES),
        json.dumps(EU_NAMNAKT_RULES),
        json.dumps(TRIGGER_SRC, indent=2),
        json.dumps(EU_TRIGGER_SRC_ENG),
        json.dumps(EU_RULES_ENG),
    )


def export_grammar():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "grammar.js").write_text(build_grammar_js(), encoding="utf-8")


def build_datasets_js():
    namedlaws = load_namedlaws(datasets.NAMEDLAWS)
    namedlaws_data = {
        "current": dict(namedlaws),
        "history": {k: list(v) for k, v in namedlaws._history.items()},
    }

    abbrevs = load_abbreviations(datasets.NAMEDLAWS)
    abbrevs_data = {
        "current": dict(abbrevs),
        "history": {k: list(v) for k, v in abbrevs._history.items()},
    }

    namedacts = load_namedacts(datasets.NAMEDACTS)
    citation_rules = resolve._citation_rules()
    namedcases = datasets.load_namedcases()
    treaty_names = json.loads((REPO_ROOT / "ferenda" / "lib" / "data" / "treaty_names.json").read_text(encoding="utf-8"))
    citation_names = resolve.citation_names()
    citation_series = resolve._series()
    try:
        casenumbers = datasets.load_casenumbers()
    except (AssertionError, FileNotFoundError):
        casenumbers = json.loads((REPO_ROOT / "test" / "files" / "dv" / "casenumbers.json").read_text(encoding="utf-8"))
    emd_respondents = datasets.load_emd_respondents()

    return """// Auto-generated by slopcheck/scripts/export-lagrum.py - DO NOT EDIT MANUALLY

export const NAMEDLAWS_DATA = %s;

export const ABBREVIATIONS_DATA = %s;

export const NAMEDACTS_DATA = %s;

export const TREATIES_DATA = %s;

export const TREATY_PIN_DATA = %s;

export const FS_DESIGNATIONS = %s;

export const FS_SLUG = %s;

export const JO_ARSBERATTELSE = %s;

export const NOLAW = new Set(%s);

export const LAW_SYNONYMS = new Set(%s);

export const ORDINALS = %s;

export const INDEFINITE_HEADS = %s;

export const EDPB_NAMES = %s;

export const WP29_GROUP = %s;

export const EDPB_FOUNDED = %s;

export const ATTRIBUTE_ORDER = %s;

export const FRAGMENT_LETTERS = %s;

export const EU_KEYS = %s;

export const NAMESPACES = %s;

export const CITATION_SERIES = %s;

export const CITATION_NAMES = %s;

export const NAMEDCASES_DATA = %s;

export const TREATY_NAMES_DATA = %s;

export const CASENUMBERS_DATA = %s;

export const EMD_RESPONDENTS_DATA = %s;
""" % (
        json.dumps(namedlaws_data, indent=2, ensure_ascii=False),
        json.dumps(abbrevs_data, indent=2, ensure_ascii=False),
        json.dumps(namedacts, indent=2, ensure_ascii=False),
        json.dumps(TREATIES, indent=2, ensure_ascii=False),
        json.dumps(TREATY_PIN, indent=2, ensure_ascii=False),
        json.dumps(FS_DESIGNATIONS, indent=2, ensure_ascii=False),
        json.dumps(FS_SLUG, indent=2, ensure_ascii=False),
        json.dumps(_jo_arsberattelse(), indent=2, ensure_ascii=False),
        json.dumps(sorted(NOLAW), ensure_ascii=False),
        json.dumps(sorted(LAW_SYNONYMS), ensure_ascii=False),
        json.dumps(ORDINALS, indent=2, ensure_ascii=False),
        json.dumps(INDEFINITE_HEADS, indent=2, ensure_ascii=False),
        json.dumps(list(EDPB_NAMES), indent=2, ensure_ascii=False),
        json.dumps(WP29_GROUP),
        json.dumps(LagrumParser.EDPB_FOUNDED),
        json.dumps(ATTRIBUTE_ORDER, indent=2),
        json.dumps(FRAGMENT_LETTERS, indent=2),
        json.dumps(list(EU_KEYS), indent=2),
        json.dumps(citation_rules["namespaces"], indent=2),
        json.dumps(citation_series, indent=2, ensure_ascii=False),
        json.dumps(citation_names, indent=2, ensure_ascii=False),
        json.dumps(namedcases, indent=2, ensure_ascii=False),
        json.dumps(treaty_names, indent=2, ensure_ascii=False),
        json.dumps(casenumbers, indent=2, ensure_ascii=False),
        json.dumps(emd_respondents, indent=2, ensure_ascii=False),
    )


def export_datasets():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "datasets.js").write_text(build_datasets_js(), encoding="utf-8")


def export_casenames():
    src = REPO_ROOT / "ferenda" / "hudoc" / "data" / "casenames.json"
    dest = OUTPUT_DIR / "casenames.json"
    if src.exists():
        dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")


def main():
    export_grammar()
    export_datasets()
    export_casenames()
    print("Exported grammar.js, datasets.js, and casenames.json to", OUTPUT_DIR)


if __name__ == "__main__":
    main()
